name: UserTeleportPortals
version: '1.0.2'
main: dev.tomasgng.UserTeleportPortals
api-version: '1.20'
authors: [ TomasGnG ]
description: Create simple and balanced teleportation portals.

commands:
  userteleportportals:
    aliases: utp